---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-delayed-pvc
spec:
  storageClassName: delayed-binding-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  