---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-inmediate-pvc
spec:
  # No need to define a storageClassName, it will use the default one
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  